# GEHC CONFIDENTIAL
#
# Copyright (c) 2026, 2026, GE HealthCare
# All Rights Reserved
#
# This unpublished material is proprietary to GE HealthCare. The methods and
# techniques described herein are considered trade secrets and/or
# confidential. Reproduction or distribution, in whole or in part, is
# forbidden except by express written permission of GE HealthCare.
# GE is a trademark of General Electric Company used under trademark license.

#!/usr/bin/env python3
"""Copy a DICOM folder and fix selected compliance issues on copied files.

Module overview:
- Input: a folder containing top-level ``*.dcm`` files.
- Output: a copied folder where each DICOM is normalized according to
    deterministic compliance rules.
- Constraint: no new UID is generated by this module.

Main workflow:
1. Copy ``input_dir`` to ``output_dir``.
2. Iterate over each top-level DICOM file in ``output_dir``.
3. Apply metadata/sequence fixes in-place.
4. Save file only when at least one fix was applied.

Important constants:
- DICOM tags are defined as module constants (for example
    ``SERIES_INSTANCE_UID``, ``REFERENCED_SOP_INSTANCE_UID``).
- Sequence-level constraints are defined in
    ``EXPECTED_REFERENCED_SOP_CLASS_BY_SEQUENCE``.
- Required SOP Class UIDs for detached management sequences are stored in
    ``DETACHED_*`` constants.

The script is deterministic and never generates new UID values. It only:
- reuses existing valid UIDs already present in the object context, and/or
- repairs UID syntax when possible (for example, leading zero cleanup).

Fixes implemented:
1) (0020,000E) Series Instance UID invalid syntax:
    - repair existing UID syntax without generating a new UID.

2) (0028,0034) Pixel Aspect Ratio in Icon Image Sequence:
    - remove from all items of (0088,0200).

3) (0018,0082) Inversion Time conditional presence:
    - remove when sequence is not identified as inversion recovery.

4) (7FE0,0010) Pixel Data in private sequence items:
    - recursively remove from private SQ items.

5) (0008,1150)/(0008,1155) Referenced SOP UIDs in sequence items:
    - fix empty/invalid values using existing context UIDs when possible,
    - enforce sequence-specific SOP Class UIDs for:
      * (0008,1110) Referenced Study Sequence -> Detached Study Management SOP Class,
      * (0008,1120) Referenced Patient Sequence -> Detached Patient Management SOP Class,
      * (0008,1125) Referenced Visit Sequence -> Detached Visit Management SOP Class,
    - avoid values equal/derived from root Study Instance UID in these sequences,
    - remove unrecoverable invalid items.

6) (0010,21C0) Pregnancy Status invalid value:
    - normalize value '0' to 4 (Unknown).

7) Coded sequence items (for example *CodeSequence):
    - enforce presence of at least one of (0008,0100)/(0008,0119)/(0008,0120),
    - enforce non-empty (0008,0104) Code Meaning (filled from existing code value when possible),
    - remove invalid/unrecoverable coded items,
    - remove coded sequences that become empty after cleanup.

8) (0010,1010) Patient's Age malformed syntax/length:
    - normalize to AS format ``NNNU`` (e.g. ``41`` -> ``041Y``) when reparable.

9) (0040,1001) Requested Procedure ID empty:
    - fill from Accession Number (0008,0050) or Study ID (0020,0010) when empty,
      so the element stays present and compliant with the mutual 1C condition
      between (0040,1001) and (0032,1060) Requested Procedure Description.

10) Private Creator duplication in same private group:
    - remove duplicate private creator elements when same identifier appears
      more than once in one dataset/group.

11) (0040,9210) LUT Label wrong VR/VM:
        - rewrite element as SH VM=1 with best-effort text extraction from
            existing value.

12) (0040,9096) Real World Value Mapping Sequence – missing required elements:
        - fill LUT Label (0040,9210) when absent: ``LINEAR`` when slope/intercept
            present, ``TABULAR`` when LUT data present, otherwise ``LABEL``.
        - fill LUT Explanation (0028,3003) when absent with a descriptive default
            derived from the private Philips tag or the mapping type.
        - fill Measurement Units Code Sequence (0040,08EA) when absent with a
            dimensionless UCUM item (code ``1``, scheme ``UCUM``, meaning
            ``no units``).
        - fill Real World Value First/Last Value Mapped (0040,9216)/(0040,9211)
            when absent and LUT Data is not present: range [0, 2^BitsStored-1]
            derived from root dataset BitsStored (0028,0101), defaulting to 65535.
"""

import argparse
import re
import shutil
from pathlib import Path
from typing import Iterable, List, Optional, Set, Tuple

import pydicom
from pydicom.dataset import Dataset
from pydicom.sequence import Sequence
from pydicom.tag import Tag
from pydicom.uid import UID


# DICOM tag constants used by the fixer.
# Grouping rationale:
# - UID and reference tags
# - sequence/content tags
# - coded terminology tags
SERIES_INSTANCE_UID = Tag(0x0020, 0x000E)
SOP_CLASS_UID = Tag(0x0008, 0x0016)
SOP_INSTANCE_UID = Tag(0x0008, 0x0018)
SPECIFIC_CHARACTER_SET = Tag(0x0008, 0x0005)
STUDY_INSTANCE_UID = Tag(0x0020, 0x000D)
FRAME_OF_REFERENCE_UID = Tag(0x0020, 0x0052)
REFERENCED_SOP_CLASS_UID = Tag(0x0008, 0x1150)
REFERENCED_SOP_INSTANCE_UID = Tag(0x0008, 0x1155)
REFERENCED_STUDY_SEQUENCE = Tag(0x0008, 0x1110)
REFERENCED_PATIENT_SEQUENCE = Tag(0x0008, 0x1120)
REFERENCED_VISIT_SEQUENCE = Tag(0x0008, 0x1125)
ICON_IMAGE_SEQUENCE = Tag(0x0088, 0x0200)
PIXEL_ASPECT_RATIO = Tag(0x0028, 0x0034)
BODY_PART_EXAMINED = Tag(0x0018, 0x0015)
SAMPLES_PER_PIXEL = Tag(0x0028, 0x0002)
PLANAR_CONFIGURATION = Tag(0x0028, 0x0006)
INVERSION_TIME = Tag(0x0018, 0x0082)
SCANNING_SEQUENCE = Tag(0x0018, 0x0020)
SEQUENCE_NAME = Tag(0x0018, 0x0024)
PULSE_SEQUENCE_NAME = Tag(0x0018, 0x9005)
PIXEL_DATA = Tag(0x7FE0, 0x0010)
PREGNANCY_STATUS = Tag(0x0010, 0x21C0)
PATIENT_AGE = Tag(0x0010, 0x1010)
REQUESTED_PROCEDURE_ID = Tag(0x0040, 0x1001)
REQUESTED_PROCEDURE_DESCRIPTION = Tag(0x0032, 0x1060)
ACCESSION_NUMBER = Tag(0x0008, 0x0050)
STUDY_ID = Tag(0x0020, 0x0010)
LUT_LABEL = Tag(0x0040, 0x9210)
REAL_WORLD_VALUE_MAPPING_SEQUENCE = Tag(0x0040, 0x9096)
RWV_LUT_DATA = Tag(0x0040, 0x9212)
RWV_SLOPE = Tag(0x0040, 0x9225)
RWV_INTERCEPT = Tag(0x0040, 0x9224)
LUT_EXPLANATION = Tag(0x0028, 0x3003)
MEASUREMENT_UNITS_CODE_SEQUENCE = Tag(0x0040, 0x08EA)
RWV_FIRST_VALUE_MAPPED = Tag(0x0040, 0x9216)
RWV_LAST_VALUE_MAPPED = Tag(0x0040, 0x9211)
BITS_STORED = Tag(0x0028, 0x0101)
CODE_VALUE = Tag(0x0008, 0x0100)
CODE_MEANING = Tag(0x0008, 0x0104)
LONG_CODE_VALUE = Tag(0x0008, 0x0119)
URN_CODE_VALUE = Tag(0x0008, 0x0120)
CODING_SCHEME_DESIGNATOR = Tag(0x0008, 0x0102)
CODING_SCHEME_VERSION = Tag(0x0008, 0x0103)

# Expected SOP Class UIDs for detached management references.
#
# These values are used to normalize (0008,1150) Referenced SOP Class UID
# when the parent sequence denotes a management-level reference.
#
# DICOM UIDs:
# - Detached Study Management SOP Class   -> 1.2.840.10008.3.1.2.3.1
# - Detached Patient Management SOP Class -> 1.2.840.10008.3.1.2.1.1
# - Detached Visit Management SOP Class   -> 1.2.840.10008.3.1.2.2.1
DETACHED_STUDY_MANAGEMENT_SOP_CLASS_UID = "1.2.840.10008.3.1.2.3.1"
DETACHED_PATIENT_MANAGEMENT_SOP_CLASS_UID = "1.2.840.10008.3.1.2.1.1"
DETACHED_VISIT_MANAGEMENT_SOP_CLASS_UID = "1.2.840.10008.3.1.2.2.1"

# Mapping from management reference sequence tag to its required
# Referenced SOP Class UID (0008,1150).
#
# The fixer uses this mapping to enforce compliant values in:
# - (0008,1110) Referenced Study Sequence
# - (0008,1120) Referenced Patient Sequence
# - (0008,1125) Referenced Visit Sequence
EXPECTED_REFERENCED_SOP_CLASS_BY_SEQUENCE = {
    REFERENCED_STUDY_SEQUENCE: DETACHED_STUDY_MANAGEMENT_SOP_CLASS_UID,
    REFERENCED_PATIENT_SEQUENCE: DETACHED_PATIENT_MANAGEMENT_SOP_CLASS_UID,
    REFERENCED_VISIT_SEQUENCE: DETACHED_VISIT_MANAGEMENT_SOP_CLASS_UID,
}

DEFAULT_PRIVATE_CODING_SCHEME_DESIGNATOR = "99LOCAL"
KNOWN_CODING_SCHEME_BY_CODE_VALUE = {
    "MEDIM": "DCM",
}
KNOWN_CODE_MEANING_BY_SCHEME_AND_VALUE = {
    ("DCM", "MEDIM"): "Portable Media Importer Equipment",
}
CODE_STRING_PATTERN = re.compile(r"^[A-Z0-9_ ]{1,16}$")
AGE_STRING_PATTERN = re.compile(r"^[0-9]{3}[DWMY]$")


class FileFixResult:
    """Per-file processing result.

    Attributes:
        path: Path of the processed DICOM file.
        changed: True when at least one fix was applied.
        changes: Human-readable list of applied fix descriptions.
        error: Optional error message when processing failed.
    """

    def __init__(self, path, changed=False, changes=None, error=None):
        """Initialize a result container.

        Args:
            path: Processed file path.
            changed: Initial changed flag.
            changes: Optional initial list of change messages.
            error: Optional initial error message.
        """
        self.path = path
        self.changed = changed
        self.changes = list(changes) if changes is not None else []
        self.error = error


def is_uid_valid(uid_value: object) -> bool:
    """Return True when the provided value is a syntactically valid DICOM UID.

    Args:
        uid_value: Value to validate.

    Returns:
        True when UID syntax is valid, False otherwise.
    """
    if not isinstance(uid_value, str) or not uid_value:
        return False
    try:
        return bool(UID(uid_value).is_valid)
    except Exception:
        return False


def repair_uid_syntax(uid_value: object) -> Optional[str]:
    """Repair UID syntax without generating a new identifier.

    Current strategy: remove leading zeros in numeric components
    (e.g. "03619" -> "3619") and keep the same component order.
    """
    uid_text = str(uid_value).strip()
    if not uid_text:
        return None

    raw_parts = uid_text.split(".")
    if any(part == "" for part in raw_parts):
        # Avoid inventing missing components from malformed separators.
        return None

    repaired_parts = []  # type: List[str]
    for part in raw_parts:
        if not part.isdigit():
            # Keep behavior conservative: repair only numeric components.
            return None
        repaired_parts.append(part.lstrip("0") or "0")

    candidate = ".".join(repaired_parts)
    return candidate if is_uid_valid(candidate) else None


def is_empty_value(value: object) -> bool:
    """Return True when a DICOM element value should be treated as empty.

    Args:
        value: DICOM element value.

    Returns:
        True when value is ``None`` or empty according to DICOM-oriented heuristics.
    """
    if value is None:
        return True
    if isinstance(value, str):
        return value.strip() == ""
    if isinstance(value, bytes):
        return value.strip() == b""
    if isinstance(value, Iterable) and not isinstance(value, (str, bytes)):
        try:
            # Prefer direct length check for sized iterables.
            return len(value) == 0  # type: ignore[arg-type]
        except TypeError:
            # For non-sized iterables, check if any element exists without
            # materializing the entire iterable.
            iterator = iter(value)
            try:
                next(iterator)
            except StopIteration:
                return True
            return False
    return False


def is_code_string_valid(value: object) -> bool:
    """Return True when the value is a syntactically valid DICOM CS string."""
    if value is None:
        return False
    text = str(value).strip()
    return bool(CODE_STRING_PATTERN.fullmatch(text))


def normalize_code_string(value: object, max_length: int = 16) -> Optional[str]:
    """Normalize a free-text value into a conservative DICOM CS-compatible string."""
    text = str(value).strip().upper()
    if not text:
        return None

    normalized = re.sub(r"[^A-Z0-9_ ]+", "_", text)
    normalized = re.sub(r"[ _]+", "_", normalized).strip("_")
    if not normalized or len(normalized) > max_length:
        return None
    return normalized


def normalize_patient_age(ds: Dataset, changes: List[str], path: str) -> bool:
    """Normalize Patient's Age to DICOM AS format ``NNNU`` when possible."""
    if PATIENT_AGE not in ds:
        return False

    raw_value = str(ds[PATIENT_AGE].value).strip().upper()
    if AGE_STRING_PATTERN.fullmatch(raw_value):
        return False

    digits = "".join(ch for ch in raw_value if ch.isdigit())
    unit = next((ch for ch in raw_value if ch in ("D", "W", "M", "Y")), "Y")

    if not digits:
        del ds[PATIENT_AGE]
        changes.append(
            "Removed unrecoverable Patient's Age (0010,1010) at {} because AS value was invalid."
            .format(path)
        )
        return True

    age_number = min(int(digits), 999)
    normalized = "{:03d}{}".format(age_number, unit)
    if normalized == raw_value:
        return False

    ds[PATIENT_AGE].value = normalized
    changes.append(
        "Normalized Patient's Age (0010,1010) at {}: {!r} -> {!r}."
        .format(path, raw_value, normalized)
    )
    return True


def normalize_requested_procedure_id(
    ds: Dataset,
    root_ds: Dataset,
    changes: List[str],
    path: str,
) -> bool:
    """Fill Requested Procedure ID when present with an empty value.

    (0040,1001) and (0032,1060) Requested Procedure Description are mutually
    1C: each is required if the other is absent. Removing an empty (0040,1001)
    can trigger a "missing when condition is true" error when the validator
    considers the presence of the Request Attributes Sequence itself as the
    activation condition. This function fills the element instead, so it stays
    present and compliant regardless of whether the description is present.

    Fallback priority: Accession Number (0008,0050) from the same dataset or
    root, Study ID (0020,0010) from the same dataset or root, then the string
    ``\"UNKNOWN\"``.
    """
    if REQUESTED_PROCEDURE_ID not in ds or not is_empty_value(ds[REQUESTED_PROCEDURE_ID].value):
        return False

    fallback = None
    for tag in (ACCESSION_NUMBER, STUDY_ID):
        for candidate_ds in (ds, root_ds):
            if tag in candidate_ds and not is_empty_value(candidate_ds[tag].value):
                candidate = str(candidate_ds[tag].value).strip()[:16]
                if candidate:
                    fallback = candidate
                    break
        if fallback is not None:
            break

    if fallback is None:
        fallback = "UNKNOWN"

    ds[REQUESTED_PROCEDURE_ID].value = fallback
    changes.append(
        "Filled empty Requested Procedure ID (0040,1001) at {} with {!r}."
        .format(path, fallback)
    )
    return True


def best_effort_lut_label_text(value: object) -> Optional[str]:
    """Extract a SH-compatible LUT Label text from arbitrary malformed values."""
    if is_empty_value(value):
        return None

    if isinstance(value, str):
        text = value.strip()
        return text[:16] if text else None

    if isinstance(value, Iterable) and not isinstance(value, (str, bytes)):
        values = list(value)
        if len(values) == 0:
            return None

        # Some malformed datasets encode ASCII text as VM>1 signed shorts.
        if all(isinstance(v, int) for v in values):
            buffer = bytearray()
            for number in values:
                unsigned = int(number) & 0xFFFF
                buffer.extend(unsigned.to_bytes(2, byteorder="little", signed=False))
            decoded = bytes(buffer).decode("latin1", errors="ignore").replace("\x00", "").strip()
            if decoded:
                return decoded[:16]

        text = str(values[0]).strip()
        return text[:16] if text else None

    text = str(value).strip()
    return text[:16] if text else None


def normalize_lut_label(ds: Dataset, changes: List[str], path: str) -> bool:
    """Rewrite LUT Label element with official VR/VM (SH, VM=1)."""
    if LUT_LABEL not in ds:
        return False

    elem = ds[LUT_LABEL]
    if elem.VR == "SH" and not is_empty_value(elem.value) and elem.VM == 1:
        return False

    normalized_text = best_effort_lut_label_text(elem.value)
    if normalized_text is None:
        del ds[LUT_LABEL]
        changes.append(
            "Removed invalid LUT Label (0040,9210) at {} because value could not be normalized to SH VM=1."
            .format(path)
        )
        return True

    # Recreate the element to force official VR and single-value VM.
    del ds[LUT_LABEL]
    ds.add_new(LUT_LABEL, "SH", normalized_text)
    changes.append(
        "Normalized LUT Label (0040,9210) at {} to VR=SH VM=1 with value {!r}."
        .format(path, normalized_text)
    )
    return True


def deduplicate_private_creators(ds: Dataset, changes: List[str], path: str) -> bool:
    """Remove duplicate private creator identifiers inside each private group."""
    changed = False
    groups = sorted({elem.tag.group for elem in ds if elem.tag.group % 2 == 1})

    for group in groups:
        seen_values = set()  # type: Set[str]
        to_delete = []  # type: List[Tag]
        for elem in ds:
            if elem.tag.group != group:
                continue
            if elem.tag.element > 0x00FF:
                continue
            value = str(elem.value).strip()
            if value == "":
                continue
            if value in seen_values:
                to_delete.append(elem.tag)
            else:
                seen_values.add(value)

        for tag in to_delete:
            removed_value = ds[tag].value
            del ds[tag]
            changes.append(
                "Removed duplicate Private Creator {} at {} (value {!r}) in group ({:04X},xxxx)."
                .format(tag, path, removed_value, group)
            )
            changed = True

    return changed


def _rwvms_default_label_and_explanation(item: Dataset) -> Tuple[str, str]:
    """Return (label, explanation) defaults for one RWVMS item.

    Priority for explanation: Philips private tag (2001,10C1) inside the item,
    then derive from the mapping type (LINEAR / TABULAR).
    """
    has_lut_data = RWV_LUT_DATA in item and not is_empty_value(item[RWV_LUT_DATA].value)
    has_slope = RWV_SLOPE in item and not is_empty_value(item[RWV_SLOPE].value)
    has_intercept = RWV_INTERCEPT in item and not is_empty_value(item[RWV_INTERCEPT].value)

    if has_lut_data:
        label = "TABULAR"
        explanation = "LUT mapping"
    elif has_slope or has_intercept:
        label = "LINEAR"
        explanation = "Linear mapping"
    else:
        label = "LABEL"
        explanation = ""

    # Prefer Philips private description when readily available.
    philips_private_text_tag = Tag(0x2001, 0x10C1)
    if philips_private_text_tag in item and not is_empty_value(item[philips_private_text_tag].value):
        explanation = str(item[philips_private_text_tag].value).strip()[:64]

    return label, explanation


def fix_real_world_value_mapping_sequence(
    ds: Dataset,
    root_ds: Dataset,
    changes: List[str],
    path: str,
) -> bool:
    """Fill required elements missing from Real World Value Mapping Sequence items.

    Applies to each item of (0040,9096) present in ``ds``. For every item
    the following attributes are added when absent:

    - (0040,9210) LUT Label              (SH, Type 1 – always required)
    - (0028,3003) LUT Explanation        (LO, Type 1 – always required)
    - (0040,08EA) Measurement Units Code Sequence  (SQ, Type 1 – always required)
    - (0040,9216)/(0040,9211) Real World Value First/Last Value Mapped (US, 1C)
      required when LUT Data (0040,9212) is absent.

    The pixel range [0, 2^BitsStored-1] is derived from root dataset
    (0028,0101) BitsStored; 65535 is used when BitsStored is unavailable.
    """
    if REAL_WORLD_VALUE_MAPPING_SEQUENCE not in ds:
        return False

    changed = False
    bits_stored = None
    if BITS_STORED in root_ds:
        try:
            bits_stored = int(root_ds[BITS_STORED].value)
        except Exception:
            bits_stored = None
    max_pixel_value = (1 << bits_stored) - 1 if bits_stored else 65535

    for idx, item in enumerate(ds[REAL_WORLD_VALUE_MAPPING_SEQUENCE].value):
        item_path = "{}/{}[{}]".format(path, REAL_WORLD_VALUE_MAPPING_SEQUENCE, idx)
        default_label, default_explanation = _rwvms_default_label_and_explanation(item)

        # (0040,9210) LUT Label – Type 1, always required, SH.
        if LUT_LABEL not in item or is_empty_value(item[LUT_LABEL].value):
            if LUT_LABEL in item:
                item[LUT_LABEL].value = default_label
            else:
                item.add_new(LUT_LABEL, "SH", default_label)
            changes.append(
                "Filled missing LUT Label (0040,9210) at {} with {!r}."
                .format(item_path, default_label)
            )
            changed = True

        # (0028,3003) LUT Explanation – Type 1, always required, LO.
        if LUT_EXPLANATION not in item or is_empty_value(item[LUT_EXPLANATION].value):
            if LUT_EXPLANATION in item:
                item[LUT_EXPLANATION].value = default_explanation
            else:
                item.add_new(LUT_EXPLANATION, "LO", default_explanation)
            changes.append(
                "Filled missing LUT Explanation (0028,3003) at {} with {!r}."
                .format(item_path, default_explanation)
            )
            changed = True

        # (0040,08EA) Measurement Units Code Sequence – Type 1, always required.
        if MEASUREMENT_UNITS_CODE_SEQUENCE not in item or is_empty_value(
            item[MEASUREMENT_UNITS_CODE_SEQUENCE].value
        ):
            unit_item = Dataset()
            unit_item.add_new(CODE_VALUE, "SH", "1")
            unit_item.add_new(CODING_SCHEME_DESIGNATOR, "SH", "UCUM")
            unit_item.add_new(CODE_MEANING, "LO", "no units")
            if MEASUREMENT_UNITS_CODE_SEQUENCE in item:
                item[MEASUREMENT_UNITS_CODE_SEQUENCE].value = Sequence([unit_item])
            else:
                item.add_new(MEASUREMENT_UNITS_CODE_SEQUENCE, "SQ", Sequence([unit_item]))
            changes.append(
                "Filled missing Measurement Units Code Sequence (0040,08EA) at {} "
                "with dimensionless UCUM item.".format(item_path)
            )
            changed = True

        # (0040,9216)/(0040,9211) pixel range – 1C when LUT Data absent.
        has_lut_data = RWV_LUT_DATA in item and not is_empty_value(item[RWV_LUT_DATA].value)
        has_us_range = (
            RWV_FIRST_VALUE_MAPPED in item and not is_empty_value(item[RWV_FIRST_VALUE_MAPPED].value)
            and RWV_LAST_VALUE_MAPPED in item and not is_empty_value(item[RWV_LAST_VALUE_MAPPED].value)
        )
        if not has_lut_data and not has_us_range:
            item.add_new(RWV_FIRST_VALUE_MAPPED, "US", 0)
            item.add_new(RWV_LAST_VALUE_MAPPED, "US", max_pixel_value)
            changes.append(
                "Filled missing Real World Value pixel range (0040,9216)/(0040,9211) "
                "at {} with [0, {}].".format(item_path, max_pixel_value)
            )
            changed = True

    return changed


def normalized_existing_uid(ds: Dataset, tag: Tag) -> Optional[str]:
    """Return a valid UID from dataset, optionally syntax-repaired.

    Args:
        ds: Dataset to inspect.
        tag: UID tag to read.

    Returns:
        A valid UID string if available/reparable, otherwise None.
    """
    if tag not in ds:
        return None
    value = ds[tag].value
    if is_empty_value(value):
        return None

    uid_text = str(value).strip()
    if is_uid_valid(uid_text):
        return uid_text

    return repair_uid_syntax(uid_text)


def is_uid_derived_from(base_uid: Optional[str], candidate_uid: Optional[str]) -> bool:
    """Return True when candidate UID equals or is derived from base UID."""
    if not base_uid or not candidate_uid:
        return False
    return candidate_uid == base_uid or candidate_uid.startswith(base_uid + ".")


def is_uid_related_to_any(base_uids: Iterable[Optional[str]], candidate_uid: Optional[str]) -> bool:
    """Return True when candidate UID equals/derives from any UID in base_uids."""
    for base_uid in base_uids:
        if is_uid_derived_from(base_uid, candidate_uid):
            return True
    return False


def collect_referenced_sop_instance_uids(ds: Dataset) -> List[str]:
    """Collect unique valid ``(0008,1155)`` values from nested sequence items.

    Args:
        ds: Root dataset.

    Returns:
        Ordered list of unique referenced SOP Instance UIDs.
    """
    collected = []  # type: List[str]
    seen = set()  # type: Set[str]

    def walk(container: Dataset) -> None:
        for elem in container:
            if elem.VR != "SQ":
                continue
            for item in elem.value:
                if REFERENCED_SOP_INSTANCE_UID in item:
                    candidate = normalized_existing_uid(item, REFERENCED_SOP_INSTANCE_UID)
                    if candidate and candidate not in seen:
                        seen.add(candidate)
                        collected.append(candidate)
                walk(item)

    walk(ds)
    return collected


def best_existing_reference_instance_uid(
    item: Dataset,
    parent_ds: Dataset,
    root_ds: Dataset,
    parent_sequence_tag: Tag,
) -> Optional[str]:
    """Choose a reusable UID candidate for ``(0008,1155)`` without generating one.

    Args:
        item: Current sequence item being repaired.
        parent_ds: Parent dataset containing the sequence.
        root_ds: Root DICOM dataset.
        parent_sequence_tag: Tag of the parent sequence.

    Returns:
        Best existing valid UID candidate or None.
    """
    candidates = [
        normalized_existing_uid(item, REFERENCED_SOP_INSTANCE_UID),
        normalized_existing_uid(item, SOP_INSTANCE_UID),
        normalized_existing_uid(parent_ds, SOP_INSTANCE_UID),
    ]

    candidates.extend(collect_referenced_sop_instance_uids(root_ds))

    candidates.extend([
        normalized_existing_uid(root_ds, STUDY_INSTANCE_UID),
        normalized_existing_uid(root_ds, SERIES_INSTANCE_UID),
        normalized_existing_uid(root_ds, FRAME_OF_REFERENCE_UID),
        normalized_existing_uid(root_ds, SOP_INSTANCE_UID),
    ])

    root_sop_instance_uid = normalized_existing_uid(root_ds, SOP_INSTANCE_UID)
    root_study_instance_uid = normalized_existing_uid(root_ds, STUDY_INSTANCE_UID)
    root_series_instance_uid = normalized_existing_uid(root_ds, SERIES_INSTANCE_UID)
    root_frame_of_reference_uid = normalized_existing_uid(root_ds, FRAME_OF_REFERENCE_UID)
    root_management_uids = (
        root_sop_instance_uid,
        root_study_instance_uid,
        root_series_instance_uid,
        root_frame_of_reference_uid,
    )
    avoid_root_uid = parent_sequence_tag in (
        REFERENCED_STUDY_SEQUENCE,
        REFERENCED_PATIENT_SEQUENCE,
        REFERENCED_VISIT_SEQUENCE,
    )

    for candidate in candidates:
        if candidate is None:
            continue
        if avoid_root_uid and is_uid_related_to_any(root_management_uids, candidate):
            continue
        return candidate

    return None


def ensure_management_reference_sequences(ds: Dataset, changes: List[str]) -> bool:
    """Ensure key management reference sequences are not left empty.

    Args:
        ds: Dataset to update.
        changes: Mutable list collecting textual changes.

    Returns:
        True if dataset was modified.
    """
    changed = False
    root_sop_instance_uid = normalized_existing_uid(ds, SOP_INSTANCE_UID)
    root_study_instance_uid = normalized_existing_uid(ds, STUDY_INSTANCE_UID)
    root_series_instance_uid = normalized_existing_uid(ds, SERIES_INSTANCE_UID)
    root_frame_of_reference_uid = normalized_existing_uid(ds, FRAME_OF_REFERENCE_UID)
    forbidden_roots = (
        root_sop_instance_uid,
        root_study_instance_uid,
        root_series_instance_uid,
        root_frame_of_reference_uid,
    )

    reusable_uids = [
        uid
        for uid in collect_referenced_sop_instance_uids(ds)
        if not is_uid_related_to_any(forbidden_roots, uid)
    ]

    for seq_tag, expected_sop_class_uid in EXPECTED_REFERENCED_SOP_CLASS_BY_SEQUENCE.items():
        if seq_tag not in ds:
            continue

        sequence = ds[seq_tag].value
        if len(sequence) > 0:
            continue

        if len(reusable_uids) == 0:
            changes.append(
                "Could not repopulate empty sequence {} because no reusable Referenced SOP Instance UID "
                "was available without violating root UID constraints.".format(seq_tag)
            )
            continue

        new_item = Dataset()
        new_item.add_new(REFERENCED_SOP_CLASS_UID, "UI", expected_sop_class_uid)
        new_item.add_new(REFERENCED_SOP_INSTANCE_UID, "UI", reusable_uids[0])
        ds[seq_tag].value = Sequence([new_item])
        changes.append(
            "Repopulated empty sequence {} with one compliant reference item.".format(seq_tag)
        )
        changed = True

    return changed


def normalize_pregnancy_status(ds: Dataset, changes: List[str], path: str) -> bool:
    """Fix invalid Pregnancy Status value ``0`` by setting it to ``4`` (Unknown).

    Args:
        ds: Dataset to update.
        changes: Mutable list collecting textual changes.
        path: Logical path used in messages.

    Returns:
        True if dataset was modified.
    """
    if PREGNANCY_STATUS not in ds:
        return False

    raw_value = ds[PREGNANCY_STATUS].value
    try:
        as_int = int(str(raw_value).strip())
    except Exception:
        return False

    if as_int == 0:
        ds[PREGNANCY_STATUS].value = 4
        changes.append(
            "Updated Pregnancy Status (0010,21C0) from 0 to 4 (Unknown) at {}.".format(path)
        )
        return True

    return False


def remove_empty_specific_character_set(ds: Dataset, changes: List[str], path: str) -> bool:
    """Remove Specific Character Set when it is present with an empty value."""
    if SPECIFIC_CHARACTER_SET not in ds or not is_empty_value(ds[SPECIFIC_CHARACTER_SET].value):
        return False

    del ds[SPECIFIC_CHARACTER_SET]
    changes.append(
        "Removed empty Specific Character Set (0008,0005) at {} because Type 1C forbids an empty value."
        .format(path)
    )
    return True


def normalize_body_part_examined(ds: Dataset, changes: List[str], path: str) -> bool:
    """Normalize Body Part Examined into a valid DICOM CS value when possible."""
    if BODY_PART_EXAMINED not in ds:
        return False

    current_value = ds[BODY_PART_EXAMINED].value
    if is_code_string_valid(current_value):
        return False

    normalized_value = normalize_code_string(current_value)
    if normalized_value is None:
        return False

    ds[BODY_PART_EXAMINED].value = normalized_value
    changes.append(
        "Normalized Body Part Examined (0018,0015) at {}: {!r} -> {!r}."
        .format(path, current_value, normalized_value)
    )
    return True


def remove_invalid_planar_configuration(ds: Dataset, changes: List[str], path: str) -> bool:
    """Remove Planar Configuration when Samples per Pixel does not require it."""
    if PLANAR_CONFIGURATION not in ds:
        return False

    samples_per_pixel = None
    if SAMPLES_PER_PIXEL in ds:
        try:
            samples_per_pixel = int(str(ds[SAMPLES_PER_PIXEL].value).strip())
        except Exception:
            samples_per_pixel = None

    if samples_per_pixel is not None and samples_per_pixel > 1:
        return False

    old_value = ds[PLANAR_CONFIGURATION].value
    del ds[PLANAR_CONFIGURATION]
    changes.append(
        "Removed Planar Configuration (0028,0006) value {!r} at {} because Samples per Pixel does not require it."
        .format(old_value, path)
    )
    return True


def existing_coding_scheme_designator_for_code(root_ds: Dataset, code_values: Iterable[str]) -> Optional[str]:
    """Find a reusable coding scheme designator for one of the provided code values."""
    wanted_values = {value for value in code_values if value}
    if not wanted_values:
        return None

    for elem in root_ds.iterall():
        if elem.VR != "SQ":
            continue
        for item in elem.value:
            existing_values = set()
            for tag in (CODE_VALUE, LONG_CODE_VALUE, URN_CODE_VALUE):
                if tag in item and not is_empty_value(item[tag].value):
                    existing_values.add(str(item[tag].value).strip())
            if wanted_values.isdisjoint(existing_values):
                continue
            if CODING_SCHEME_DESIGNATOR in item and not is_empty_value(item[CODING_SCHEME_DESIGNATOR].value):
                return str(item[CODING_SCHEME_DESIGNATOR].value).strip()

    return None


def inferred_coding_scheme_designator(item: Dataset, root_ds: Dataset, code_values: Iterable[str]) -> Optional[str]:
    """Infer a Coding Scheme Designator from known mappings or existing dataset content."""
    for code_value in code_values:
        candidate = KNOWN_CODING_SCHEME_BY_CODE_VALUE.get(code_value)
        if candidate:
            return candidate

    candidate = existing_coding_scheme_designator_for_code(root_ds, code_values)
    if candidate:
        return candidate

    if CODE_VALUE in item or LONG_CODE_VALUE in item:
        return DEFAULT_PRIVATE_CODING_SCHEME_DESIGNATOR

    return None


def fix_referenced_sop_uids(
    item: Dataset,
    parent_ds: Dataset,
    root_ds: Dataset,
    parent_sequence_tag: Tag,
    changes: List[str],
    path: str,
) -> Tuple[bool, bool]:
    """Fix empty/invalid Referenced SOP UIDs from existing context; remove item if unrecoverable.

    Args:
        item: Sequence item to repair.
        parent_ds: Parent dataset.
        root_ds: Root dataset.
        parent_sequence_tag: Tag of the containing sequence.
        changes: Mutable list collecting textual changes.
        path: Logical path used in messages.

    Returns:
        Tuple ``(changed, remove_item)``.
    """
    changed = False
    if REFERENCED_SOP_CLASS_UID not in item and REFERENCED_SOP_INSTANCE_UID not in item:
        return False, False

    expected_class = EXPECTED_REFERENCED_SOP_CLASS_BY_SEQUENCE.get(parent_sequence_tag)
    class_candidate = expected_class or (
        normalized_existing_uid(item, SOP_CLASS_UID)
        or normalized_existing_uid(parent_ds, SOP_CLASS_UID)
        or normalized_existing_uid(root_ds, SOP_CLASS_UID)
    )
    instance_candidate = best_existing_reference_instance_uid(item, parent_ds, root_ds, parent_sequence_tag)

    unresolved = False

    if REFERENCED_SOP_CLASS_UID in item:
        current_class_uid = normalized_existing_uid(item, REFERENCED_SOP_CLASS_UID)
        if current_class_uid is None or (expected_class is not None and current_class_uid != expected_class):
            if class_candidate is None:
                unresolved = True
            else:
                old = item[REFERENCED_SOP_CLASS_UID].value
                item[REFERENCED_SOP_CLASS_UID].value = class_candidate
                changes.append(
                    "Fixed Referenced SOP Class UID (0008,1150) at {}: {!r} -> {!r}."
                    .format(path, old, class_candidate)
                )
                changed = True

    if REFERENCED_SOP_INSTANCE_UID in item:
        current_instance_uid = normalized_existing_uid(item, REFERENCED_SOP_INSTANCE_UID)
        root_sop_instance_uid = normalized_existing_uid(root_ds, SOP_INSTANCE_UID)
        root_study_instance_uid = normalized_existing_uid(root_ds, STUDY_INSTANCE_UID)
        root_series_instance_uid = normalized_existing_uid(root_ds, SERIES_INSTANCE_UID)
        root_frame_of_reference_uid = normalized_existing_uid(root_ds, FRAME_OF_REFERENCE_UID)
        root_management_uids = (
            root_sop_instance_uid,
            root_study_instance_uid,
            root_series_instance_uid,
            root_frame_of_reference_uid,
        )
        invalid_for_sequence = (
            parent_sequence_tag in (
                REFERENCED_STUDY_SEQUENCE,
                REFERENCED_PATIENT_SEQUENCE,
                REFERENCED_VISIT_SEQUENCE,
            )
            and is_uid_related_to_any(root_management_uids, current_instance_uid)
        )

        if current_instance_uid is None or invalid_for_sequence:
            if instance_candidate is None:
                unresolved = True
            else:
                old = item[REFERENCED_SOP_INSTANCE_UID].value
                item[REFERENCED_SOP_INSTANCE_UID].value = instance_candidate
                changes.append(
                    "Fixed Referenced SOP Instance UID (0008,1155) at {}: {!r} -> {!r}."
                    .format(path, old, instance_candidate)
                )
                changed = True

    if unresolved:
        changes.append(
            "Removed sequence item at {} because referenced SOP UIDs were empty/invalid "
            "and could not be repaired without generating new UIDs.".format(path)
        )
        return changed, True

    return changed, False


def fix_code_item_fields(item: Dataset, root_ds: Dataset, changes: List[str], path: str) -> Tuple[bool, bool]:
    """Fix missing code fields for coded items when possible; otherwise remove invalid item.

    Args:
        item: Coded item to inspect.
        changes: Mutable list collecting textual changes.
        path: Logical path used in messages.

    Returns:
        Tuple ``(changed, remove_item)``.
    """
    has_code_context = any(
        tag in item
        for tag in (
            CODE_VALUE,
            LONG_CODE_VALUE,
            URN_CODE_VALUE,
            CODE_MEANING,
            CODING_SCHEME_DESIGNATOR,
            CODING_SCHEME_VERSION,
        )
    )

    if not has_code_context:
        return False, False

    return fix_coded_sequence_item(item, root_ds, changes, path)


def fix_coded_sequence_item(
    item: Dataset,
    root_ds: Dataset,
    changes: List[str],
    path: str,
) -> Tuple[bool, bool]:
    """Fix an item from a *CodeSequence.

    Rules:
    - one of (0008,0100)/(0008,0119)/(0008,0120) must be present and non-empty
    - (0008,0102) must be present and non-empty when Code Value or Long Code Value is used
    - (0008,0104) must be present and non-empty
    If not repairable from existing values, remove the item.
    """
    changed = False

    code_candidates = []
    for tag in (CODE_VALUE, LONG_CODE_VALUE, URN_CODE_VALUE):
        if tag in item and not is_empty_value(item[tag].value):
            code_candidates.append(str(item[tag].value).strip())

    if len(code_candidates) == 0:
        changes.append(
            "Removed *CodeSequence item at {} because all of "
            "(0008,0100)/(0008,0119)/(0008,0120) were missing or empty.".format(path)
        )
        return changed, True

    if (CODE_VALUE in item or LONG_CODE_VALUE in item) and (
        CODING_SCHEME_DESIGNATOR not in item or is_empty_value(item[CODING_SCHEME_DESIGNATOR].value)
    ):
        scheme_designator = inferred_coding_scheme_designator(item, root_ds, code_candidates)
        if scheme_designator is None:
            changes.append(
                "Removed *CodeSequence item at {} because Coding Scheme Designator (0008,0102) "
                "was required but could not be inferred from existing context.".format(path)
            )
            return changed, True

        if CODING_SCHEME_DESIGNATOR in item:
            item[CODING_SCHEME_DESIGNATOR].value = scheme_designator
        else:
            item.add_new(CODING_SCHEME_DESIGNATOR, "SH", scheme_designator)
        changes.append(
            "Filled missing Coding Scheme Designator (0008,0102) at {} with {!r}."
            .format(path, scheme_designator)
        )
        changed = True

    if CODE_MEANING not in item or is_empty_value(item[CODE_MEANING].value):
        fallback = code_candidates[0]
        if CODE_MEANING in item:
            item[CODE_MEANING].value = fallback
        else:
            item.add_new(CODE_MEANING, "LO", fallback)
        changes.append(
            "Filled missing Code Meaning (0008,0104) at {} from existing code value {!r}."
            .format(path, fallback)
        )
        changed = True

    current_scheme_designator = None
    if CODING_SCHEME_DESIGNATOR in item and not is_empty_value(item[CODING_SCHEME_DESIGNATOR].value):
        current_scheme_designator = str(item[CODING_SCHEME_DESIGNATOR].value).strip()

    for code_value in code_candidates:
        expected_meaning = KNOWN_CODE_MEANING_BY_SCHEME_AND_VALUE.get(
            (current_scheme_designator, code_value)
        )
        if expected_meaning is None:
            continue
        current_meaning = str(item[CODE_MEANING].value).strip()
        if current_meaning == expected_meaning:
            continue
        item[CODE_MEANING].value = expected_meaning
        changes.append(
            "Normalized Code Meaning (0008,0104) at {} for scheme/code ({!r}, {!r}): {!r} -> {!r}."
            .format(path, current_scheme_designator, code_value, current_meaning, expected_meaning)
        )
        changed = True
        break

    return changed, False


def fix_nested_items(ds: Dataset, root_ds: Dataset, changes: List[str], path: str = "root") -> bool:
    """Recursively apply item-level fixes in nested sequences.

    Args:
        ds: Dataset/sub-dataset to inspect.
        root_ds: Root dataset (context for reuse constraints).
        changes: Mutable list collecting textual changes.
        path: Logical path used in messages.

    Returns:
        True if at least one update was applied.
    """
    changed = normalize_pregnancy_status(ds, changes, path)
    changed = remove_empty_specific_character_set(ds, changes, path) or changed
    changed = normalize_body_part_examined(ds, changes, path) or changed
    changed = remove_invalid_planar_configuration(ds, changes, path) or changed
    changed = normalize_patient_age(ds, changes, path) or changed
    changed = normalize_requested_procedure_id(ds, root_ds, changes, path) or changed
    changed = normalize_lut_label(ds, changes, path) or changed
    changed = deduplicate_private_creators(ds, changes, path) or changed
    changed = fix_real_world_value_mapping_sequence(ds, root_ds, changes, path) or changed
    empty_sequences_to_delete = []  # type: List[Tag]

    for elem in ds:
        if elem.VR != "SQ":
            continue

        for idx in range(len(elem.value) - 1, -1, -1):
            item = elem.value[idx]
            item_path = "{}/{}[{}]".format(path, elem.tag, idx)

            ref_changed, remove_ref_item = fix_referenced_sop_uids(
                item,
                ds,
                root_ds,
                elem.tag,
                changes,
                item_path,
            )
            changed = changed or ref_changed
            if remove_ref_item:
                del elem.value[idx]
                changed = True
                continue

            code_changed, remove_code_item = fix_code_item_fields(item, root_ds, changes, item_path)
            changed = changed or code_changed
            if remove_code_item:
                del elem.value[idx]
                changed = True
                continue

            if fix_nested_items(item, root_ds, changes, item_path):
                changed = True

        if elem.keyword and elem.keyword.endswith("CodeSequence") and len(elem.value) == 0:
            empty_sequences_to_delete.append(elem.tag)

    for seq_tag in empty_sequences_to_delete:
        del ds[seq_tag]
        changes.append(
            "Removed empty sequence {} because it contained zero items after fix-up."
            .format(seq_tag)
        )
        changed = True

    return changed


def scanning_sequence_tokens(ds: Dataset) -> Set[str]:
    """Extract normalized upper-cased scanning sequence tokens.

    Args:
        ds: Dataset to inspect.

    Returns:
        Set of normalized token strings.
    """
    if SCANNING_SEQUENCE not in ds:
        return set()
    value = ds[SCANNING_SEQUENCE].value
    if isinstance(value, str):
        return {value.upper()}
    if isinstance(value, Iterable) and not isinstance(value, (str, bytes)):
        return {str(v).upper() for v in value}
    return {str(value).upper()}


def is_inversion_recovery_sequence(ds: Dataset) -> bool:
    """Heuristically detect inversion recovery acquisition.

    Args:
        ds: Dataset to inspect.

    Returns:
        True when IR hints are found, False otherwise.
    """
    tokens = scanning_sequence_tokens(ds)
    if "IR" in tokens:
        return True

    for tag in (SEQUENCE_NAME, PULSE_SEQUENCE_NAME):
        if tag in ds:
            text = str(ds[tag].value).upper()
            if "IR" in text:
                return True
    return False


def remove_icon_pixel_aspect_ratio(ds: Dataset, changes: List[str]) -> bool:
    """Remove Pixel Aspect Ratio from all Icon Image Sequence items.

    Args:
        ds: Dataset to update.
        changes: Mutable list collecting textual changes.

    Returns:
        True if at least one item was modified.
    """
    changed = False
    if ICON_IMAGE_SEQUENCE in ds:
        for idx, item in enumerate(ds[ICON_IMAGE_SEQUENCE].value):
            if PIXEL_ASPECT_RATIO in item:
                del item[PIXEL_ASPECT_RATIO]
                changes.append(
                    f"Removed Pixel Aspect Ratio (0028,0034) from Icon Image Sequence item {idx}."
                )
                changed = True
    return changed


def remove_private_item_pixel_data(ds: Dataset, changes: List[str], path: str = "root") -> bool:
    """Recursively remove Pixel Data found inside private sequence items.

    Args:
        ds: Dataset/sub-dataset to inspect.
        changes: Mutable list collecting textual changes.
        path: Logical path used in messages.

    Returns:
        True if at least one item was modified.
    """
    changed = False
    for elem in ds:
        if elem.VR != "SQ":
            continue

        is_private_sq = elem.tag.group % 2 == 1
        for idx, item in enumerate(elem.value):
            item_path = f"{path}/{elem.tag}[{idx}]"
            if is_private_sq and PIXEL_DATA in item:
                del item[PIXEL_DATA]
                changes.append(f"Removed Pixel Data (7FE0,0010) from private sequence item {item_path}.")
                changed = True

            if remove_private_item_pixel_data(item, changes, item_path):
                changed = True

    return changed


def fix_dataset(ds: Dataset) -> Tuple[bool, List[str]]:
    """Apply all configured DICOM fixes to one dataset and report performed changes.

    Notes:
    - No new UID is generated by this function.
    - Invalid items can be removed when they cannot be repaired from existing values.
    """
    changes = []  # type: List[str]
    changed = False

    if SERIES_INSTANCE_UID in ds:
        current_uid = ds[SERIES_INSTANCE_UID].value
        if not is_uid_valid(current_uid):
            repaired_uid = repair_uid_syntax(current_uid)
            if not repaired_uid:
                raise ValueError(
                    "Series Instance UID (0020,000E) is invalid and cannot be repaired "
                    "without generating a new UID."
                )
            ds[SERIES_INSTANCE_UID].value = repaired_uid
            changes.append(
                f"Repaired invalid Series Instance UID (0020,000E): {current_uid!r} -> {repaired_uid!r}."
            )
            changed = True

    if remove_icon_pixel_aspect_ratio(ds, changes):
        changed = True

    if remove_empty_specific_character_set(ds, changes, "root"):
        changed = True

    if normalize_body_part_examined(ds, changes, "root"):
        changed = True

    if remove_invalid_planar_configuration(ds, changes, "root"):
        changed = True

    if normalize_patient_age(ds, changes, "root"):
        changed = True

    if normalize_requested_procedure_id(ds, ds, changes, "root"):
        changed = True

    if normalize_lut_label(ds, changes, "root"):
        changed = True

    if deduplicate_private_creators(ds, changes, "root"):
        changed = True

    if fix_real_world_value_mapping_sequence(ds, ds, changes, "root"):
        changed = True

    if INVERSION_TIME in ds and not is_inversion_recovery_sequence(ds):
        old = ds[INVERSION_TIME].value
        del ds[INVERSION_TIME]
        changes.append(
            f"Removed Inversion Time (0018,0082) value {old!r} because sequence is not inversion recovery."
        )
        changed = True

    if remove_private_item_pixel_data(ds, changes):
        changed = True

    if normalize_pregnancy_status(ds, changes, "root"):
        changed = True

    if fix_nested_items(ds, ds, changes):
        changed = True

    if ensure_management_reference_sequences(ds, changes):
        changed = True

    return changed, changes


def process_file(path: Path) -> FileFixResult:
    """Process one DICOM file and return its result.

    Args:
        path: DICOM file path.

    Returns:
        A ``FileFixResult`` describing modifications/errors.
    """
    result = FileFixResult(path=path)
    try:
        ds = pydicom.dcmread(path, force=True)
        changed, changes = fix_dataset(ds)
        result.changed = changed
        result.changes = changes
        if changed:
            ds.save_as(path, write_like_original=False)
    except Exception as exc:
        result.error = str(exc)
    return result


def copy_input_folder(input_dir: Path, output_dir: Path, overwrite: bool) -> None:
    """Copy source folder to destination.

    Args:
        input_dir: Source folder.
        output_dir: Destination folder.
        overwrite: When True, existing destination is removed first.

    Raises:
        FileExistsError: If destination exists and ``overwrite`` is False.
    """
    if output_dir.exists():
        if not overwrite:
            raise FileExistsError(
                f"Output directory already exists: {output_dir}. Use --overwrite to replace it."
            )
        shutil.rmtree(output_dir)

    shutil.copytree(input_dir, output_dir)


def iter_dicom_files(root: Path) -> List[Path]:
    """Return top-level ``*.dcm`` files from a directory.

    Args:
        root: Folder to scan.

    Returns:
        Sorted list of top-level DICOM file paths.
    """
    # The requested workflow targets a directory containing DICOM files.
    return sorted(p for p in root.glob("*.dcm") if p.is_file())


def main() -> int:
    """CLI entry point.

    Returns:
        ``0`` when no per-file processing error occurred, otherwise ``1``.
    """
    parser = argparse.ArgumentParser(
        description="Copy a folder and fix selected DICOM compliance issues on copied files."
    )
    parser.add_argument("input_dir", type=Path, help="Folder containing source DICOM files")
    parser.add_argument(
        "output_dir",
        nargs="?",
        type=Path,
        help="Destination folder. Default: <input_dir>_corrected",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Delete output folder if it already exists",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print per-file modifications",
    )

    args = parser.parse_args()
    input_dir: Path = args.input_dir.resolve()
    output_dir: Path = (
        args.output_dir.resolve()
        if args.output_dir
        else input_dir.parent / f"{input_dir.name}_corrected"
    )

    if not input_dir.exists() or not input_dir.is_dir():
        raise NotADirectoryError(f"Input directory does not exist or is not a directory: {input_dir}")

    if output_dir == input_dir or input_dir in output_dir.parents:
        raise ValueError("Output directory must be outside the input directory.")

    copy_input_folder(input_dir, output_dir, overwrite=args.overwrite)

    files = iter_dicom_files(output_dir)
    changed_count = 0
    error_count = 0

    for path in files:
        result = process_file(path)
        if result.error:
            error_count += 1
            print(f"[ERROR] {path}: {result.error}")
            continue

        if result.changed:
            changed_count += 1
            if args.verbose:
                print(f"[FIXED] {path}")
                for change in result.changes:
                    print(f"  - {change}")
        elif args.verbose:
            print(f"[OK] {path}")

    print("\nSummary")
    print(f"- Copied folder: {input_dir} -> {output_dir}")
    print(f"- DICOM files scanned: {len(files)}")
    print(f"- DICOM files modified: {changed_count}")
    print(f"- DICOM files with errors: {error_count}")
    return 0 if error_count == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())